language: go

jobs:
  include:
    - stage: "Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.9.x
      script: go build
    - stage: "Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.9.x
      script: go test ./... -race
    - stage: "Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.10.x
      script: go build
    - stage: "Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.10.x
      script: go test ./... -race
    - stage: "Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.11.x
      script: go build
    - stage: "Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.11.x
      script: go test ./... -race
    - stage: "Build"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.13.x
      script: go build
    - stage: "Test"
      if: branch = master OR branch = develop OR branch =~ /release\/.*/ OR branch =~ /hotfix\/.*/ OR branch =~ /v[0-9]+[0-9.]*/
      os: linux
      go: 1.13.x
      script: go test ./... -race
    - stage: "Build"
      os: linux
      go: 1.12.x
      script: go build
    - stage: "Test"
      os: linux
      go: 1.12.x
      before_install: go get github.com/mattn/goveralls
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: 
        - go test ./... -race -coverprofile=c.out
      after_script:
        - $GOPATH/bin/goveralls -coverprofile=c.out -service=travis-ci
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: "Build"
      os: osx
      go: 1.12.x
      script: go build
    - stage: "Test"
      os: osx
      go: 1.12.x
      script: go test ./... -race